apiVersion: v1
kind: Service
metadata:
  name: ping1-service
spec:
  type: NodePort
  selector:
    app: ping1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081
  sessionAffinity: ClientIP
